"""Ticket templates by category with varying sentiment levels."""

CUSTOMER_TIERS = ["standard", "premium", "enterprise"]

CUSTOMER_NAMES = [
    "Sarah Johnson",
    "Michael Chen",
    "Emily Rodriguez",
    "James Williams",
    "Maria Garcia",
    "David Kim",
    "Jessica Martinez",
    "Robert Taylor",
    "Amanda Brown",
    "Christopher Lee",
    "Jennifer Davis",
    "Daniel Wilson",
    "Ashley Anderson",
    "Matthew Thomas",
    "Laura Jackson",
    "Andrew White",
    "Stephanie Harris",
    "Joshua Clark",
    "Nicole Lewis",
    "Kevin Robinson",
]

TICKET_TEMPLATES = {
    "billing": [
        {
            "subject": "Overcharged on last invoice",
            "body": "I was charged $299 instead of $199 on my last invoice. This is the second time this has happened. Please fix this immediately and refund the difference.",
            "expected_category": "billing",
            "expected_priority": "high",
            "sentiment_range": (0.5, 0.7),
            "ideal_response_keywords": ["refund", "invoice", "apologize", "corrected"],
        },
        {
            "subject": "Question about billing cycle",
            "body": "Hi, I just wanted to understand when my next billing cycle starts. I signed up mid-month and I'm not sure if I'll be charged for a full month or prorated. Thanks!",
            "expected_category": "billing",
            "expected_priority": "low",
            "sentiment_range": (0.0, 0.2),
            "ideal_response_keywords": ["billing cycle", "prorated", "charge"],
        },
        {
            "subject": "UNACCEPTABLE - Double charged AGAIN!!!",
            "body": "THIS IS THE THIRD TIME I'VE BEEN DOUBLE CHARGED! I am FURIOUS. I want a full refund AND compensation for the time I've wasted dealing with this. If this isn't resolved TODAY I'm canceling my account and contacting the BBB. This is absolutely UNACCEPTABLE!!!",
            "expected_category": "billing",
            "expected_priority": "urgent",
            "sentiment_range": (0.85, 1.0),
            "ideal_response_keywords": ["apologize", "refund", "escalate", "priority"],
        },
        {
            "subject": "Need updated invoice for tax purposes",
            "body": "Could you send me an updated invoice that includes our company tax ID? We need it for our quarterly filing. Our tax ID is registered under Acme Corp.",
            "expected_category": "billing",
            "expected_priority": "medium",
            "sentiment_range": (0.0, 0.15),
            "ideal_response_keywords": ["invoice", "tax", "updated"],
        },
        {
            "subject": "Refund request for unused subscription",
            "body": "I forgot to cancel my subscription last month and didn't use the service at all. I'd like to request a refund for the last month. I've been a loyal customer for 2 years and hope you can help.",
            "expected_category": "billing",
            "expected_priority": "medium",
            "sentiment_range": (0.2, 0.4),
            "ideal_response_keywords": ["refund", "policy", "review"],
        },
    ],
    "technical": [
        {
            "subject": "Can't log in to my account",
            "body": "I've been trying to log in for the past hour and keep getting an 'Invalid credentials' error. I've reset my password twice and it still doesn't work. I have an important deadline today.",
            "expected_category": "technical",
            "expected_priority": "high",
            "sentiment_range": (0.4, 0.6),
            "ideal_response_keywords": ["login", "password", "reset", "access"],
        },
        {
            "subject": "API returning 500 errors intermittently",
            "body": "Our integration with your API has been returning 500 errors about 30% of the time since yesterday. This is affecting our production environment. Here's the error trace: RequestID: abc-123-def. Can you investigate?",
            "expected_category": "technical",
            "expected_priority": "urgent",
            "sentiment_range": (0.5, 0.7),
            "ideal_response_keywords": ["API", "error", "investigating", "status"],
        },
        {
            "subject": "How to set up SSO integration",
            "body": "We're looking to set up SSO with our Okta instance. Could you point me to the right documentation or walk me through the steps? We're on the enterprise plan.",
            "expected_category": "technical",
            "expected_priority": "medium",
            "sentiment_range": (0.0, 0.15),
            "ideal_response_keywords": ["SSO", "documentation", "setup", "Okta"],
        },
        {
            "subject": "Data export feature is broken",
            "body": "When I try to export my data as CSV, the download starts but the file is always empty (0 bytes). I've tried different browsers and clearing cache. This worked fine last week.",
            "expected_category": "technical",
            "expected_priority": "high",
            "sentiment_range": (0.3, 0.5),
            "ideal_response_keywords": ["export", "CSV", "investigating", "workaround"],
        },
        {
            "subject": "Performance has degraded significantly",
            "body": "Page load times have gone from ~2s to over 15s in the last few days. Our team of 50 people can barely get any work done. This is severely impacting our productivity and we're considering alternatives if this isn't fixed soon.",
            "expected_category": "technical",
            "expected_priority": "urgent",
            "sentiment_range": (0.6, 0.8),
            "ideal_response_keywords": ["performance", "investigating", "priority", "update"],
        },
    ],
    "account": [
        {
            "subject": "Want to upgrade to enterprise plan",
            "body": "Our team has grown to 200 people and we need the enterprise features. Can you walk me through the upgrade process and pricing?",
            "expected_category": "account",
            "expected_priority": "medium",
            "sentiment_range": (0.0, 0.1),
            "ideal_response_keywords": ["enterprise", "upgrade", "pricing", "features"],
        },
        {
            "subject": "Considering cancellation",
            "body": "I've been a customer for 3 years but honestly the product hasn't kept up with competitors. Unless something changes significantly, I'll be moving to a competitor next quarter. Thought you should know.",
            "expected_category": "account",
            "expected_priority": "high",
            "sentiment_range": (0.4, 0.6),
            "ideal_response_keywords": ["value", "feedback", "retention", "improvements"],
        },
        {
            "subject": "Need to add team members",
            "body": "How do I add 5 new team members to our account? And will we be charged immediately or at the next billing cycle?",
            "expected_category": "account",
            "expected_priority": "low",
            "sentiment_range": (0.0, 0.1),
            "ideal_response_keywords": ["team", "add", "seats", "billing"],
        },
        {
            "subject": "CANCEL MY ACCOUNT NOW",
            "body": "I want my account cancelled IMMEDIATELY. Your service has been nothing but problems and your support team never resolves anything. I want a full refund for the remaining subscription period. Do NOT try to talk me out of this.",
            "expected_category": "account",
            "expected_priority": "urgent",
            "sentiment_range": (0.85, 1.0),
            "ideal_response_keywords": ["cancel", "process", "refund", "understand"],
        },
        {
            "subject": "Feature request: custom dashboards",
            "body": "It would be great if we could create custom dashboards with our own KPI widgets. Right now we have to export data and build dashboards in another tool. Is this on your roadmap?",
            "expected_category": "account",
            "expected_priority": "low",
            "sentiment_range": (0.0, 0.15),
            "ideal_response_keywords": ["feature", "roadmap", "dashboard", "feedback"],
        },
    ],
    "product": [
        {
            "subject": "Is the Pro plan compatible with Salesforce?",
            "body": "We use Salesforce as our CRM and want to make sure the Pro plan integrates with it before we upgrade. Can you confirm what Salesforce features are supported?",
            "expected_category": "product",
            "expected_priority": "medium",
            "sentiment_range": (0.0, 0.15),
            "ideal_response_keywords": ["Salesforce", "integration", "compatible", "features"],
        },
        {
            "subject": "Bug: notifications not working on mobile",
            "body": "Push notifications stopped working on the iOS app about a week ago. I've checked my notification settings and they're all enabled. Android seems fine. Running iOS 18.2.",
            "expected_category": "product",
            "expected_priority": "high",
            "sentiment_range": (0.2, 0.4),
            "ideal_response_keywords": ["notifications", "iOS", "investigating", "update"],
        },
        {
            "subject": "Documentation for webhook events",
            "body": "Where can I find documentation for all the webhook event types? I need to set up custom automation based on specific events but the docs seem incomplete.",
            "expected_category": "product",
            "expected_priority": "medium",
            "sentiment_range": (0.1, 0.25),
            "ideal_response_keywords": ["webhook", "documentation", "events", "API"],
        },
        {
            "subject": "Missing feature from latest update",
            "body": "After your latest update, the batch processing feature seems to have been removed. We rely on this heavily for our daily operations. Was this intentional? We need this back ASAP.",
            "expected_category": "product",
            "expected_priority": "urgent",
            "sentiment_range": (0.5, 0.7),
            "ideal_response_keywords": ["batch processing", "update", "feature", "investigating"],
        },
        {
            "subject": "What file formats does the import tool support?",
            "body": "Quick question - does the import tool support JSON files or only CSV? We have data in JSON format and would prefer not to convert it.",
            "expected_category": "product",
            "expected_priority": "low",
            "sentiment_range": (0.0, 0.1),
            "ideal_response_keywords": ["import", "JSON", "CSV", "format"],
        },
    ],
    "general": [
        {
            "subject": "Thank you for the great support!",
            "body": "Just wanted to say thank you to your support team for helping me resolve my issue last week. The response was fast and the solution worked perfectly. Keep up the great work!",
            "expected_category": "general",
            "expected_priority": "low",
            "sentiment_range": (0.0, 0.05),
            "ideal_response_keywords": ["thank", "feedback", "glad", "help"],
        },
        {
            "subject": "Partnership inquiry",
            "body": "I'm reaching out on behalf of TechStart Inc. We're interested in exploring a potential partnership or integration with your platform. Who would be the right person to discuss this with?",
            "expected_category": "general",
            "expected_priority": "medium",
            "sentiment_range": (0.0, 0.1),
            "ideal_response_keywords": ["partnership", "contact", "team", "discuss"],
        },
        {
            "subject": "Compliance and data residency questions",
            "body": "We're a healthcare company evaluating your platform. We need to know about your SOC 2 compliance, HIPAA BAA availability, and data residency options. Can you provide documentation on these?",
            "expected_category": "general",
            "expected_priority": "high",
            "sentiment_range": (0.0, 0.15),
            "ideal_response_keywords": ["compliance", "SOC 2", "HIPAA", "documentation"],
        },
    ],
}
